config/routes.rb
Spree::Core::Engine.add_routes do
  namespace :admin do
    resources :reviews, only: [:index, :destroy, :edit, :update] do
      member do
        get :approve
      end
      resources :feedback_reviews, only: [:index, :destroy]
    end
    resource :review_settings, only: [:edit, :update]
  end

  resources :products, only: [] do
    resources :reviews, only: [:index, :new, :create] do
    end
  end
  post '/reviews/:review_id/feedback(.:format)' => 'feedback_reviews#create', as: :feedback_reviews
end

app/controllers/spree/admin/reviews_controller.rb
class Spree::Admin::ReviewsController < Spree::Admin::ResourceController
  helper Spree::ReviewsHelper

  def index
    @reviews = collection
  end

  def approve
    review = Spree::Review.find(params[:id])
    if review.update_attribute(:approved, true)
      flash[:notice] = Spree.t(:info_approve_review)
    else
      flash[:error] = Spree.t(:error_approve_review)
    end
    redirect_to admin_reviews_path
  end

  def edit
    return if @review.product
    flash[:error] = Spree.t(:error_no_product)
    redirect_to admin_reviews_path
  end

  private

  def collection
    params[:q] ||= {}
    @search = Spree::Review.ransack(params[:q])
    @collection = @search.result.includes([:product, :user, :feedback_reviews]).page(params[:page]).per(params[:per_page])
  end
end

app/controllers/spree/reviews_controller.rb
class Spree::ReviewsController < Spree::StoreController
  helper Spree::BaseHelper
  before_action :load_product, only: [:index, :new, :create]
  rescue_from ActiveRecord::RecordNotFound, with: :render_404

  def index
    @approved_reviews = Spree::Review.approved.where(product: @product)
  end

  def new
    @review = Spree::Review.new(product: @product)
    authorize! :create, @review
  end

  # save if all ok
  def create
    params[:review][:rating].sub!(/\s*[^0-9]*\z/, '') unless params[:review][:rating].blank?

    @review = Spree::Review.new(review_params)
    @review.product = @product
    @review.user = spree_current_user if spree_user_signed_in?
    @review.ip_address = request.remote_ip
    @review.locale = I18n.locale.to_s if Spree::Reviews::Config[:track_locale]

    authorize! :create, @review
    if @review.save
      flash[:notice] = Spree.t(:review_successfully_submitted)
      redirect_to spree.product_path(@product)
    else
      render :new
    end
  end

  private

  def load_product
    @product = Spree::Product.friendly.find(params[:product_id])
  end

  def permitted_review_attributes
    [:rating, :title, :review, :name, :show_identifier]
  end

  def review_params
    params.require(:review).permit(permitted_review_attributes)
  end
end

app/helpers/spree/reviews_helper.rb
module Spree::ReviewsHelper
  def star(the_class)
    content_tag(:span, ' &#10030; '.html_safe, class: the_class)
  end

  def mk_stars(m)
    (1..5).collect { |n| n <= m ? star('lit') : star('unlit') }.join
  end

  def txt_stars(n, show_out_of = true)
    res = Spree.t(:star, count: n)
    res += " #{Spree.t('out_of_5')}" if show_out_of
    res
  end
end

app/views/spree/admin/reviews/_form.html.erb
<%= render 'spree/shared/error_messages', target: @review %>

<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :review %>
  <%= f.text_area :review, wrap: 'virtual', rows: 10, cols: 60, class: 'form-control' %>
</div>

<% if Spree::Reviews::Config[:track_locale] %>
  <div class="form-group">
    <%= f.label :locale %>
    <%= f.select :locale, I18n.available_locales.map { |lc| [t(lc, default: lc.to_s), lc.to_s] }, {}, class: 'select2' %>
  </div>
<% end %>

app/views/spree/admin/reviews/edit.html.erb
<% content_for :page_title do %>
	<%= Spree.t(:editing_review_for_html, link: link_to(@review.product.name, product_path(@review.product))) %>
<% end %>

<%= form_for [:admin, @review] do |f| %>
	<div class="row">
		<div class="col-md-6">
			<%= render 'form', f: f %>
		</div>
		<div class="col-md-6">
			<% unless @review.title.blank? %>
				<h2><%= @review.title %></h2>
			<% end %>
			<blockquote>
				<%= simple_format(@review.review) %>
			</blockquote>
		</div>
	</div>
	<%= render 'spree/admin/shared/edit_resource_links' %>
<% end %>

app/views/spree/admin/reviews/index.html.erb
<% content_for :page_title do %>
	<%= Spree.t(:reviews) %>
<% end %>

<% content_for :table_filter do %>
  <div data-hook="admin_reviews_index_search">
    <%= search_form_for [:admin, @search] do |f| %>
			<div class="row">
				<div class="col-md-6">
					<div class="form-group">
						<%= label_tag :q_name_cont, Spree::Review.human_attribute_name(:user) %>
						<%= f.text_field :name_cont, size: 25, class: 'form-control' %>
					</div>
				</div>

				<div class="col-md-6">
					<div class="form-group">
						<%= label_tag :q_title_cont, Spree::Review.human_attribute_name(:title) %>
						<%= f.text_field :title_cont, size: 25, class: 'form-control' %>
					</div>
				</div>
			</div>

			<div class="row">
				<div class="col-md-6">
					<div class="form-group">
						<%= label_tag :q_review_cont, Spree::Review.human_attribute_name(:review) %>
						<%= f.text_field :review_cont, size: 25, class: 'form-control' %>
					</div>
				</div>

				<div class="col-md-6">
					<div class="form-group">
						<%= label_tag :q_approved_eq, Spree.t(:approval_status) %>
						<%= f.select :approved_eq, [[Spree.t(:all), nil], [Spree.t(:approved_reviews), true], [Spree.t(:unapproved_reviews), false]], {}, class: 'select2' %>
					</div>
				</div>
			</div>
			<div class="form-actions" data-hook="admin_reviews_index_search_buttons">
				<%= button Spree.t(:filter_results), 'search' %>
			</div>
    <% end %>
  </div>
<% end %>

<%= render 'spree/admin/shared/index_table_options', collection: @reviews %>

<% if @reviews.any? %>
	<table class="table" id="listing_reviews">
		<thead>
			<tr>
				<th><%= sort_link @search, :product, Spree.t(:product) %></th>
				<th><%= sort_link @search, :rating, Spree::Review.human_attribute_name(:rating) %></th>
				<th><%= Spree.t(:feedback) %></th>
				<th><%= sort_link @search, :user, Spree::Review.human_attribute_name(:user) %></th>
				<th><%= sort_link @search, :ip_address, Spree::Review.human_attribute_name(:ip_address) %></th>
				<th><%= sort_link @search, :created_at, Spree::Review.human_attribute_name(:created_at) %></th>
				<th data-hook="admin_reviews_index_header_actions" class="actions"></th>
			</tr>
		</thead>
		<tbody>
			<% @reviews.each do |review| %>
				<tr data-hook="admin_reviews_index_rows" id="<%= dom_id review %>" class="<%= cycle('odd', 'even') %>">
					<td><%= link_to_if review.product, review.product.name, product_path(review.product) %></td>
					<td><%= txt_stars(review.rating) %></td>
					<td><%= link_to "(#{review.feedback_stars}/#{review.feedback_reviews.size})", admin_review_feedback_reviews_path(review) %></td>
					<td><%= review.user_id ? link_to(review.user.try(:email), [:admin, review.user]) : Spree.t(:anonymous) %></td>
					<td><%= link_to_if review.ip_address, review.ip_address, "http://whois.domaintools.com/#{review.ip_address}", target: :blank %></td>
					<td><%= l review.created_at, format: :short %></td>
					<td data-hook="admin_reviews_index_row_actions" class="actions">
						<%= link_to_with_icon 'save', Spree.t(:approve), approve_admin_review_url(review), no_text: true, class: 'approve btn btn-default' unless review.approved %>
						<%= link_to_edit review, no_text: true, class: 'edit' %>
						<%= link_to_delete review, no_text: true %>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
<% else %>
	<div class="alert alert-info no-objects-found">
		<%= Spree.t(:no_resource_found, resource: Spree.t(:reviews)) %>
	</div>
<% end %>

<%= render 'spree/admin/shared/index_table_options', collection: @reviews %>